/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rohith.CaseData;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author rohith
 */
public class DeleteRecord extends javax.swing.JDialog {

    /**
     * Creates new form DeleteRecord
     */
    boolean flag = false;
    String dbPath;
    Connection conn;
    PreparedStatement pst,pst1;
    ResultSet rs;
    String squery;
    public static void setWindow(DeleteRecord window)
    {
        //Centralize the window
        Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
        int w=window.getSize().width;
        int h=window.getSize().height;
        int x=(dim.width - w)/2;
        int y=(dim.height -h)/2;
        window.setLocation(x,y);
        
        //set window size
        window.setSize(dim.width/2,dim.height/2);
    }
    public DeleteRecord(java.awt.Frame parent,String dbPath) {
        super(parent, true);
        this.dbPath = dbPath;
        initComponents();
        setWindow(this);
        this.setTitle("Delete Record");
        TxtS_no.setText("");
        TxtArea.setText("");
        TxtArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtS_no = new javax.swing.JTextField();
        BtnDel = new javax.swing.JButton();
        BtnRst = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.red);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("DELETE RECORD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(191, 191, 191))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Record ID:");

        TxtS_no.setText("jTextField1");
        TxtS_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtS_noActionPerformed(evt);
            }
        });
        TxtS_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtS_noKeyPressed(evt);
            }
        });

        BtnDel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        BtnDel.setText("Delete Record");
        BtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelActionPerformed(evt);
            }
        });

        BtnRst.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        BtnRst.setText("Reset");
        BtnRst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRstActionPerformed(evt);
            }
        });

        BtnCancel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        TxtArea.setColumns(20);
        TxtArea.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        TxtArea.setRows(5);
        jScrollPane1.setViewportView(TxtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtS_no, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnRst, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtS_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDel)
                    .addComponent(BtnRst)
                    .addComponent(BtnCancel))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelActionPerformed
        // TODO add your handling code here:
        conn = ConnectDB.Connect(dbPath);
        if(flag)
        {
            int reply = JOptionPane.showConfirmDialog(this, "Are you sure you want to Delete the record?");
            if(reply == JOptionPane.YES_OPTION)
            {
                try
                {
                    String query = "DELETE FROM records WHERE s_no = ?";
                    pst1 = conn.prepareStatement(query);
                    pst1.setString(1, squery);
                    pst1.execute();
                    TxtArea.setText("");
                    JOptionPane.showMessageDialog(this, "Record Deleted Successfully");
                }
                catch (SQLException ex) {
                    Logger.getLogger(DeleteRecord.class.getName()).log(Level.SEVERE, null, ex);
                }
                flag = false;
            }
            TxtS_no.requestFocus();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Press Enter after entering Record ID Field");
            TxtS_no.requestFocus();
        }
        ConnectDB.closeConnection(conn);
    }//GEN-LAST:event_BtnDelActionPerformed

    private void BtnRstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRstActionPerformed
        // TODO add your handling code here:
        flag = false;
        TxtArea.setText("");
        TxtS_no.requestFocus();
    }//GEN-LAST:event_BtnRstActionPerformed

    private void TxtS_noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtS_noKeyPressed
        // TODO add your handling code here:
        conn = ConnectDB.Connect(dbPath);
        squery = TxtS_no.getText();
        flag = false;
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            flag = true;
            try
            {
                String query = "SELECT s_no,name_client,laop_no,appeal_no,"
                + "village,reach_no FROM records WHERE s_no = ?";
                pst = conn.prepareStatement(query);
                pst.setString(1, squery);
                rs = pst.executeQuery();
                if(rs.next())
                {
                    TxtArea.append("\nName of the Client : " + rs.getString("name_client"));
                    TxtArea.append("\nName of Village : " + rs.getString("village"));
                    TxtArea.append("\nReach No. : " + rs.getString("reach_no"));
                    TxtArea.append("\nLAOP No. : " + rs.getString("laop_no"));
                    TxtArea.append("\nAppeal No. : " + rs.getString("appeal_no"));
                    TxtArea.append("\n");
                }
                else
                {
                    flag = false;
                    TxtArea.setText("");
                    JOptionPane.showMessageDialog(this, "No Records found");
                }
            }
            catch (SQLException ex) {
                Logger.getLogger(DeleteRecord.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        ConnectDB.closeConnection(conn);
    }//GEN-LAST:event_TxtS_noKeyPressed

    private void TxtS_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtS_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtS_noActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnDel;
    private javax.swing.JButton BtnRst;
    private javax.swing.JTextArea TxtArea;
    private javax.swing.JTextField TxtS_no;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
